channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - pyg
dependencies:
  - python==3.9.18
  - cmake
  - pybind11
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch3d==0.7.4
  - torchvision==0.14.1
  - torchaudio==0.13.1
  - pyg==2.3.1
  - pytorch-cluster==1.6.1
  - pytorch-scatter==2.1.1
  - exa # optional: nice ls
  - fzf # optional: fancy ctrl + R
  - pip
  - pip:
    - numpy <1.24 # certain deprecated operations were used in other deps
    - scipy
    - sophuspy==0.0.8
    - pybullet
    - trimesh<4
    - pytest
    - scikit-image
    - scikit-fmm
    - scikit-learn
    - numpy-quaternion
    - natsort
    - frozendict
    # Robots
    - opencv-python
    - pin>=2.6.17
    # Neural networks
    - openai-clip
    - timm
    - pandas>=2
    - mss
    # visualizations and debugging
    - matplotlib>=3
    # Command line tools
    - click
    # data tools
    - pillow<10.0.0
    - atomicwrites
    - loguru
    - yacs
    - h5py>=3.9
    - imageio
    - pygifsicle
    - pynput
      # - git+https://github.com/openai/CLIP.git
    - open3d>=0.17
    # For MiDaS
    #- imutils
